### ISSUE TITLE
Typo on help/info pop up

### ISSUE THREAD

**Issue by alexjbuck** [alexjbuck/airplan#27]
"Writing airplan's" should be "Writing airplans", it is plural, not possessive.

**Comment by wuteek** [comment]
Hello, I would like to work on this but I don't have permissions to contribute. Can you please assign this to me?

**Comment by alexjbuck** [comment]
Kelly, what I recommend doing is create a fork, make your changes in the
fork, and then initiate a Pull Request to request merging it back into the
main branch.
